config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true
  validates :content, length: { minimum: 1, maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @post = Post.all
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def show
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: "つぶやきを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice:"あなたのつぶやきを抹殺しました！"
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to new_post_path
    else
      render :new
    end
  end

    def post_params
      params.require(:post).permit(:content)
    end

    private

    def set_post
      @post = Post.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kadai007Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_with(model: @post, local: true) do |form| %>

<% if @post.errors.any? %>
<div id="error_explanation">
  <h2><%= @post.errors.count %>件のエラーがあります。</h2>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="post_content">
  <%= form.label :content %>
  <%= form.text_field :content %>
</div>
<%= form.submit %>

<%= link_to 'つぶやき一覧', posts_path %>
<% end %>

app/views/posts/index.html.erb
<header>
  <h1>tweet一覧</h1>
</header>
<table>
  <tr>
    <th>内容</th>
  </tr>
  <% @post.each do |post| %>
  <tr>
    <td><%= post.content %></td>
    <td><%= link_to '詳細を確認する', post_path(post) %></td>
    <td><%= link_to "つぶやきを編集する", edit_post_path(post) %></td>
    <td><%= link_to 'つぶやきを削除する', post_path(post), method: :delete %></td>
  </tr>
  <% end %>
</table>
<%= link_to '新しくつぶやく', new_post_path %>

<footer>
  <h1>(株)つぶやきしろう</h1>
</footer>

app/views/posts/new.html.erb
<%= form_with(model: @post, local: true) do |form| %>

<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= @post.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <div class="post_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>

  <%= link_to 'つぶやき一覧', posts_path %>
<% end %>

app/views/posts/show.html.erb
<h1>つぶやき詳細画面</h1>
<p>内容: <%= @post.content %></p>